# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/yusuke/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
flags:
  yi:
    vty: true
    pango: false
    emacs: true
    vim: false
extra-package-dbs: []
packages: []
extra-deps: []
resolver: lts-8.23
